### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DerrickJ1612** [DerrickJ1612/qnn_sample_apps#3]
- [ ] Add more comments to jupyter notebook explaining the workflow in depth.
- [ ] Update README.md
- [x] Update function returns (ex. def transformer still says it returns torch.tensor, when it actually returns Tuple of np.array post optimization)
- [x] Clean up comments
