### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DerrickJ1612** [DerrickJ1612/qnn_sample_apps#4]
- [x] Add code to release camera within def inference
- [x] Push empty models directory to use as 
- [x] Add Readme instructing users how to obtain models from Qualcomm AI Hub
