### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DerrickJ1612** [DerrickJ1612/qnn_sample_apps#9]
- [ ] Add unit test for ModelInference
- [x] Add argument for camera selection in main.py, default should be 0 (systems main camera)
- [ ] Develop module that will automatically download models from AI Hub, possibly save all models (type==.onnx) to an s3 bucket
